### ISSUE TITLE
Is it possible to run from a script / command line?

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#13]
Hey. The docs talk about doing everything from within building a .NET project. Is it possible to kick off Facil from the command line / F# script?

**Comment by cmeeren** [comment]
It's not officially supported. However, the generator part of Facil is just a plain .NET Core 3 console app, so you may find a way to get it working. The console app accepts a single parameter, which is the path to the folder containing the `facil.yaml`.

There may be an optimal way to achieve this that requires e.g. packing Facil as a dotnet tool in addition to the current package, but that requires some research (e.g. how to do it, and should it be a separate packag). Feel free to help out with some research. If I know exactly how to pack it, I can probably make it work officially.

But first, could you describe your workflow a bit? I have used Facil in many projects, but I have never found a need for running it as a console app.

**Comment by isaacabraham** [comment]
My workflow when trying out new libraries is generally to create a script file and start to explore :-) In this case, I simply wanted to run Facil and see what the outputs looked like.

I think in general, separating out Facil from coupling to msbuild / projects as the execution mechanism will generally lead to a more flexible result. With .NET tools, there's a decent pattern for doing this nowadays. The fact that Facil is already a console app suggests that this might not be too difficult, since my understanding of .net tools is that this is all that they are.

**Comment by cmeeren** [comment]
> will generally lead to a more flexible result

I agree, though flexibility often comes with costs (maintenance and possibly more confusing API/docs), so it must be worth it. 🙂

For exploring, instead of using a script, just create a project (class library or console app) and install Facil there. Even if Facil were to be packed as a dotnet tool, I'm not sure how well the runtime component (with the build tool) would work in FSI or in a script environment.

Since this request (currently) seems to be mainly useful for initial experimentation, and the workaround is so simple (experiment with a project instead of a script), and the current Facil package contains a build tool and I don't know the consequences of running this in a script or FSI, this is not a priority. However, if you really want it, feel free to dig up some instructions on how to accomplish this, and maybe I can work from that. 🙂

**Comment by isaacabraham** [comment]
Totally fair :-) Thanks for taking the time to think it through.
