### ISSUE TITLE
Can't pass null to a SP

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#15]
I have an SP which expects a string as a parameter, but this parameter may be null:

```fsharp
let parameters = {| Foo = 123; OptionalString = Unchecked.defaultof<string> |}
let res = DbGen.Procedures.Schema.MySp.WithConnection(conn).WithParameters(parameters).Execute()
```

This goes pop:

```
Procedure or function 'MySp' expects parameter '@optionalString', which was not supplied.
```

I've tried e.g. `null :> string` and other things but it just gets ignored. If I supply a string, the SP correctly fires.

**Comment by cmeeren** [comment]
See the readme for [how nullability is handled](https://github.com/cmeeren/Facil#how-are-default-and-nullable-parameter-values-handled).

In short, if your sproc parameter is defined as `@optionalString = NULL`, then it willl be `string option` in F#, and you then use `None` to pass `null`. This is the only supported way of passing `null` to sprocs.

For scripts, it is possible to use Facil.yaml to explicitly specify whether parameters are nullable. (This is also generally necessary, since script parameter inference is limited). This is currently not possible for procedures. I realize now that this is fairly limiting; one does not always control the sproc definition, and it is not guaranteed that all nullable parameters are defined with `NULL` as the default value in the sproc parameter list.

I will implement the ability to override nulls also for sproc parameters.

**Comment by cmeeren** [comment]
Releasing in v1.4.0 which is in the pipeline now.
