### ISSUE TITLE
Reading data into types with encapsulated values

### ISSUE THREAD

**Issue by tih2010** [cmeeren/Facil#18]
Hi!

First of all: Sorry, there is no bug or problem here, I just didn't a better way to contact you. So feel free to just delete this entry.

We are working on the business app and had it checked by Isaac (Abraham) and his team. They advised us to check out Facil. 
So far we are working with Dapper.. but with F#... well it has it's issues. So here I am.

I played around with Facil for a couple of days and like it lot. It work's like a charm.

But there is one issue that really is an obstacle for us. Of course our database has many id-columns, all of them Guids. To avoid mixing them, Isaac proposed to encapsulate them in single case union types.

```
type DocumentId = DocumentId of Guid
    with member this.Value = match this with DokumentOcrId id -> id
```

So in turn our DTOs look like this

```
type Document= { Id: DocumentId 
                              Date: DateTime
                               Title: string}
```

Maybe I overlooked something but I didn't find a way to make Facil read data into that type. The problem is that DocumentId isn't a guid - it just encapsulated a guid. 

Is there a simple way to do so?

I pondered on this some time. From a C# perspective I thought "Well.. if F# types had constructors, I could define a constructor that takes a guid as first parameter and return a nice Document-type". Unfortunately F# types don't have such constructors.

But maybe it is possible to use the `result`-option likewise. The idea is to configure Facil in way that is hands each row, that was read from the DB, to a factory-like function that converts it to the desired type.

```fsharp
...
- for: whatever.fs
      result : documentBridgeFunction
...
```

and in the code (handwritten, not generated)

```fsharp
let documentBridgeFunction id date title =
    { Id = DocumentId id
       Date = date
       Title = title }
```

Do you think, that's possible? Or is it just a bad idea? Or have I missed a point and there is already a way to achieve what we need?

Thanks in advance and best regards,
      Wolfram Bernhardt

**Comment by cmeeren** [comment]
Hi!

> First of all: Sorry, there is no bug or problem here, I just didn't a better way to contact you. So feel free to just delete this entry.

This is probably the best place for such questions regarding Facil.

> Of course our database has many id-columns, all of them Guids. To avoid mixing them, Isaac proposed to encapsulate them in single case union types.

I do that, too. I wrap more or less all my primitive types.

> So in turn our DTOs look like this

This is where I don't agree with you. That is not a DTO. A DTO should generally use only primitive types, not domain types. In Facil's case, it can often provide the DTO for you using the "table DTO" feature. Alternatively, you can just define your DTO as an alias for an anonymous record, and it will be compatible with all scripts that return (or accept) the same rows. (You could also define a proper record and configure Facil to use that as the return type, though I always use table DTOs if applicable, alternatively anonymous records.)

**Given the primitive DTO definition, It is then your job to map from the DTO to your domain code. Facil simply does not concern itself with that.**

---

The above is the answer to your question, but here's a domain driven design side-note since I just can't help myself.

This transformation may entail a simple wrapping, like you show, or it may involve parsing, e.g. when constructing a validated `PhoneNumber` type - not all strings are valid phone numbers, and the guarantees of having a separate type instead of primitives are severely diminished if you allow wrapping arbitrary invalid data. (Heck, not all GUIDs/ints are valid IDs, either - is `Guid.Empty` a valid ID? Are negative numbers, or zero, valid user IDs? Etc.)

Depending on how much you trust the data you load from the DB, e.g. greenfield vs. brownfield, you could for example throw if the data is invalid (which I do for data owned and only modified by the service in question), or you could log a warning and return no data for that field if optional (which I do for data loaded from external services; a "best-effort" kind of loading while still keeping only valid data), or if you really need to load and display/work with invalid data (I don't, so I haven't tested this), I'm sure there are good ways to use types model that while still guaranteeing 1) that e.g. a `PhoneNumber` is actually valid, and 2) that the user cannot enter invalid data; you only load invalid data from DB, not from user input.

End side-note.

---

> I pondered on this some time. From a C# perspective I thought "Well.. if F# types had constructors, I could define a constructor that takes a guid as first parameter and return a nice Document-type". Unfortunately F# types don't have such constructors.

Not sure what you mean. F# allows you to create types using constructors, static methods, module functions, etc... In any case, not relevant for Facil.

> The idea is to configure Facil in way that is hands each row, that was read from the DB, to a factory-like function that converts it to the desired type.

This is what I mean you have to do yourself. Facil is designed to load stuff from DB to DTOs, not transform it to domain code.

---

As a courtesy, here is an example of how I do it (simplified a bit; I have more generic helpers as well as custom operators to make it cleaner, but they'll probably just confuse here):

I have a file called `DbDto.fs` where I do all my DTO transformation:

```f#

module User =


  let fromDto (dto: DbGen.TableDtos.dbo.User) =  // using a Facil-generated table DTO
      {
        Id = dto.UserId |> UserId.fromInt
        FirstName = dto.FirstName |> FirstName.createOrFail
        LastName = dto.LastName |> LastName.createOrFail
        Email = dto.PrimaryEmail |> EmailAddress.createOrFail
        IsSuperuser = dto.IsSuperuser
        AvatarFileId = dto.AvatarFileId |> Option.map FileId.fromInt
      }
```

And then in `Db.fs`, which contains the actual Facil calls:

```f#
open DbDto

module User =


  let byId (connStr: string) (UserId userId) =
    User_ById
      .WithConnection(connStr)
      .WithParameters(userId)
      .AsyncExecuteSingle()
    |> Async.map (Option.map User.fromDto)


  let search (connStr: string) searchArgs =
    User_ByIds
      .WithConnection(connStr)
      .WithParameters(UserSearchArgs.toDto searchArgs)
      .AsyncExecute()
    |> Async.map (Seq.map User.fromDto >> Seq.toList)

```

---

Closing this since it's not a Facil issue and out of scope as a feature, but feel free to discuss further if anything is unclear.

**Comment by tih2010** [comment]
Hi Christer,

wow! Thanks a lot for that detailed and quick answer. I understand all of it and it more or less boils down to one point:



>>  So in turn our DTOs look like this

> This is where I don't agree with you. That is not a DTO. A DTO should generally use only primitive types, not domain types.

On one hand your are absolutely right.

On the other hand our types are only a tiny step away from DTOs. It's all primitive types and some wrapped primitive types. That's why it feels a bit... well... "inconvenient" to have to write transformation code for each DB-call in both directions. We have a huge DB, many tables, loads of columns, lots of SQL to come. :-)

Switching to Facil for us means to rework every single database-function. Well, I guess, that's the price that comes with Facil, but I think it's worth it.


So thanks again for clearing things up. I hope we meet some day when the pandemic is over. And when it happens a couple of beers is on me!

**Comment by cmeeren** [comment]
😊🍻

In your specific case, yes, it's just a tiny step away from a DTO. But firstly, that's still not a DTO, and secondly, I don't think that's a general case. In my experience, more or less all primitives can benefit from being lifted to proper domain types, with validation etc.

Furthermore, adding this capability to Facil would push users to try to adapt their domain code for easy loading from DB using Facil (e.g. no validation, different signatures), which I definitely don't want.

The domain code should be the boss, and DTOs (whether DB, API, or otherwise) should be mapped to/from the domain with suitable validation.

In any case, happy I was able to help! 😊
