### ISSUE TITLE
re: same temp table shared by two stored procedures

### ISSUE THREAD

**Issue by costa100** [cmeeren/Facil#35]
Hi,

I have a case where I have two stored procedures that access the same temp table (i.e. the table has the same structure and the same name). What is the best way to configure facil to have only one type generated in F# for the table record?

Here is the issue: I have an F# function that takes an input and it produces a list of temp table records. Facil generates two types for this temp table, one under each stored procedure. I really need one type. I was thinking that I could use a generic type with member constraints, but if the tables are big it is a pain.

Other suggestions?

Thank you!

**Comment by cmeeren** [comment]
Facil does not provide a way to share temp tables between different procedures/scripts.

However, you don't have to use member constraints yourself; as with normal parameters, Facil provides an overload that accepts a DTO object with the correct members. You can define this type once and use it both places:

```f#
type MyTempTableDto =
  { Col1: string
    Col2: int }

let myProc (connStr: string) (dtos: MyTempTableDto list) =
  MyProc.WithConnection(connStr).WithParameters(dtos |> List.map MyProc.MyTempTable.create).Execute()
```

You'd of course need to keep this type in sync with any changes to the temp table definition, but that should be trivial. I often define my own types instead of using table types (mostly when not fetching/storing the whole table) and find this simple and safe (you get compile errors if you forget it).

**Comment by costa100** [comment]
> I often define my own types instead of using table types (mostly when not fetching/storing the whole table) and find this simple and safe (you get compile errors if you forget it).

I ended up following your suggestion, and it works great because the types mapped to the temp table records have the `create (dto: ^a)` methods and I can map the manually created type to the temp table record type.

Thank you!
