### ISSUE TITLE
Add DtoAttributes for easier usage in C#

### ISSUE THREAD

**Issue by Pablo1785** [cmeeren/Facil#63]
Add a config argument that will allow adding attributes to generated F# DTO types (specifically, CLIMutable and Struct), such that it is possible to use them as "named parameters" when using from C#.

E.x.

```
// F# record
type Person = { Name: string; Age: int, ... }
```

Can only be instantiated as:
```
// C# instantiation
var person = new Person("John", 10, ...);
```

This gets very unreadable very quickly with more parameters.

Instead it would be possible to add a config like:

```
# Facil config
generatedDtoAttributes:
  - Struct
  - CLIMutable
  - ...
```

...and generate:
```
// F# record
[<Struct; CLIMutable; ...>]
type Person = { Name: string; Age: int, ... }
```

...so you can instantiate in C# like:
```
var person = new Person {
  Name = "John",
  Age = 10,
  Many = ...,
  Other = ...,
  Named = ...,
  Params = ...
};
```

**Comment by cmeeren** [comment]
Thanks for your interest in Facil!

I'm a bit split on this.

One the one hand, this is likely not a big job to add. A handful of hours, maybe. On the other hand, I'm wary of scope creep on two fronts:
1. "Since you added the option of adding custom code here, please also add it here and here."
2. "Since you have made that concession to C#, could you also make it more C# friendly in this and that way?"

Regarding the second point: Facil was made with F# usage in mind. While I haven't explicitly documented C# usage as out of scope, that has always been my thinking. Could you elaborate a bit more on how you use this from C#?

**Comment by Pablo1785** [comment]
Thank you for the very fast response, I did not expect this! :smile: 

There is a slew of C# ORMs, yes, but the one I am currently using (Entity Framework) had unfortunately reached its limits. I am bumping into all sorts of performance issues which are close to impossible to improve with EF alone - it feels like balancing a basketball on a basketball, something always breaks or slows down.

On the other hand, writing raw SQL is just setting up footguns to silently blow up prod later on. This would likely include stuff like Dapper (unless there is a way to enforce correctness which I am unaware of).

My requirements are:
- compile/build time query correctness (EF does absolutely nothing here, any complex query is a nightmare to compose because of limited LINQ translation capabilities)
- ability to do more "fine-grained" optimization (e.x. filtering before joins, re-ordering joins, avoiding implicit joins/operations, using certain SQL features like locks, partitions, complex group by's - no luck here either)
- no DB required in CI pipeline (this is where SQLProvider falls short for me)

Given the above Facil seems like the perfect fit to replace EF.

As to this being F#-first/focused/only - SQLx had really kicked the no-ORM movement into gear. I know of several Typescript projects (including Prisma, the most prominent one), that went this way. Afaik C# has no good way of doing this type of compile-time work, whereas F# does. This is why I see F# as the best tool to achieve this type of thing in the .NET ecosystem.

**Comment by cmeeren** [comment]
I see! But what about all the `Option` fields in table DTOs? I assume they aren't particularly great to use from C# because of that?

As for adding `CLIMutable`, that itself is trivial and has no ill effects for F# users. I could just add that to all table DTOs. But why do you want `Struct`? That sounds like a bad idea. If you have a record with more than 2 reference fields (e.g. strings, options), it will exceed the official MS recommendation for maximum size of structs.

**Comment by cmeeren** [comment]
Also regarding structs: Note the `ExecuteReader` methods generated by scripts. For performance-critical code where you don't want allocations (i.e., where you'd want a struct DTO), you can use `ExecuteReader` and just load manually from the `SqlDataReader`.

Given that and my reasoning above, I don't really see the benefit of providing the option of adding the `Struct` attribute. (Also, all new options are more work to implement than just doing it for all DTOs.)

**Comment by Pablo1785** [comment]
So I don't know much about TableDTOs, I am only using generated ParamDTOs and ResultDTOs.

Curly brace initialization (new Person { Name = ..., Age = ... }) would not work without the Struct annotation, since the C# type generated is a class, that is why I needed it.

As to the struct size, afaik this is just a "rule of thumb", since .NET users would mostly be used to having everything pass by reference and could easily make a big mistake copying huge value structs on accident.


But I have to admit I might have overlooked the fact that you CAN do named parameters even without the struct thing. This pretty much solves my problem, so CLIMutable would not be necessary for me.

**Comment by cmeeren** [comment]
Yes, and I was about to add that by using `CLIMutable`, you lose compile-time check for initializing all properties. If your DTO is extended with more properties, you would not get compile-time checked that you pass the new properties, giving the kinds of bugs Facil is designed to avoid. Using the constructor avoids this.

It is then my understanding that you consider this issue redundant. Since I'd prefer not doing this for the previously mentioned reasons, if you agree, feel free to close this issue.
